export const DATA_LIST = Symbol('data_list')
export const TABCURRENT = Symbol('tabCurrent')
export const ANTHOLOGY = Symbol('anthology')
export const PLAYURL = Symbol('playUrl')
export const RESET_DATA = Symbol('reset_data')
export const SHOWACTIVITY = Symbol('showActivity')
export const PAGE = Symbol('page')
export const STOPA = Symbol('stopa')
